name: TF Test

on:
  workflow_call:
    inputs:
      aws_role_arn:
        type: string
        required: true
    secrets:
      SPACELIFT_API_KEY_ENDPOINT:
        required: true
      SPACELIFT_API_KEY_ID:
        required: true
      SPACELIFT_API_KEY_SECRET:
        required: true

permissions: {}

jobs:
  tf-test:
    name: 🧪 ${{ matrix.tf }} test
    runs-on: ubuntu-latest
    permissions:
      actions: read # needed by github-action-tf-test to read workflow run context
      checks: write # needed by github-action-tf-test to write check results
      contents: read # needed by github-action-tf-test to read repository contents
      id-token: write # needed by github-action-tf-test to write id token
      pull-requests: read # needed by github-action-tf-test to read pull request context
    env:
      SPACELIFT_API_KEY_ENDPOINT: ${{ secrets.SPACELIFT_API_KEY_ENDPOINT }}
      SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_API_KEY_ID }}
      SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
    strategy:
      matrix:
        tf: [tofu, terraform]
    steps:
      - uses: masterpointio/github-action-tf-test@c1e41998f67925ac3f34e0bbcfcaa4a44d1f0cd9 # v1.0.1
        with:
          tf_type: ${{ matrix.tf }}
          aws_role_arn: ${{ inputs.aws_role_arn }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
